//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jarvis_Project_Community.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProjectResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProjectResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jarvis_Project_Community.Resources.ProjectResources", typeof(ProjectResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AzureSpeechServiceRegion].
        /// </summary>
        internal static string AzureSpeechServiceRegion {
            get {
                return ResourceManager.GetString("AzureSpeechServiceRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [AzureSpeechServiceSubscriptionKey].
        /// </summary>
        internal static string AzureSpeechServiceSubscriptionKey {
            get {
                return ResourceManager.GetString("AzureSpeechServiceSubscriptionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [GetNewExternalChatSessionIdEndpoint].
        /// </summary>
        internal static string GetNewExternalChatSessionIdEndpoint {
            get {
                return ResourceManager.GetString("GetNewExternalChatSessionIdEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [NisusAssistantEndpointID].
        /// </summary>
        internal static string NisusAssistantEndpointID {
            get {
                return ResourceManager.GetString("NisusAssistantEndpointID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PythonFilePath].
        /// </summary>
        internal static string PythonFilePath {
            get {
                return ResourceManager.GetString("PythonFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [SendExternalDeploymentCallEndpoint].
        /// </summary>
        internal static string SendExternalDeploymentCallEndpoint {
            get {
                return ResourceManager.GetString("SendExternalDeploymentCallEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [UiPathExternalAppId].
        /// </summary>
        internal static string UiPathExternalAppId {
            get {
                return ResourceManager.GetString("UiPathExternalAppId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [UiPathExternalAppSecret].
        /// </summary>
        internal static string UiPathExternalAppSecret {
            get {
                return ResourceManager.GetString("UiPathExternalAppSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [UiPathOrchestratorURL].
        /// </summary>
        internal static string UiPathOrchestratorURL {
            get {
                return ResourceManager.GetString("UiPathOrchestratorURL", resourceCulture);
            }
        }
    }
}
